### ISSUE TITLE
Using the Perfect World Platform to start cs2 wsad cannot be moved

### ISSUE THREAD

**Issue by rfvygv** [cafali/SnapKey#65] opened 2024-08-17 13:47 UTC

**Comment by cafali** [comment] 2024-08-17 14:45
This is a known problem with the CS2 Perfect World client, and unfortunately, it won't be fixed. This issue has also been mentioned previously. You can find more details here: Issue #42.

SnapKey works as intended with the global CS2 version - the problem may be caused by the client directly, not the input system of the game.

**Closed by cafali** 2024-08-17 14:45 UTC
