### ISSUE TITLE
ALT Key - Unexpected Behavior

### ISSUE THREAD

**Issue by VickyVexx** [cafali/SnapKey#52] opened 2024-08-13 19:25 UTC
Sometimes, while playing Valorant with SnapKey, if i hold one of the WASD keys, but then release it, i keep walking in the same direction, as if i was still holding down the button

i need to spam different keys repeatedly to resolve it, but that is a major hindrance while playing 

I use the G213 Logitech Keyboard.

Has anyone an idea what i could try to fix this ?

**Comment by minteeaa** [comment] 2024-08-14 05:51
try the latest release (1.2.0), updates to the input handling may remedy this issue

**Comment by VickyVexx** [comment] 2024-08-14 06:42
Will try today and wirte back

**Comment by VickyVexx** [comment] 2024-08-14 08:32
i tried one round of Team Deathmatch and the bug didn't occur 
I will play a real Match later today and write back

yesterday, the bug only occurred in real matches, not in practice mode so let's see.

**Comment by VickyVexx** [comment] 2024-08-14 10:58
Bug not resolved, played one match, keeps happening

**Comment by cafali** [comment] 2024-08-14 11:21
Hi,

I have a some friends playing Valorant with SnapKey, some even since its release 1.1.2. Nobody has mentioned a bug like this; since Valorant runs on Unreal Engine, compatibility should be there.

If you have Logitech GHUB running in the background, try disabling it. Also, make sure your keyboard has the latest firmware.
If possible, test it with another keyboard to ensure it’s not an issue with your keyboard or GHUB.

Since many keyboard and mouse software (like GHUB) access the device driver directly while running, this may cause issues, as you then have two software utilities managing the keyboard inputs (1 directly accessing the driver( GHUB)).

**Comment by VickyVexx** [comment] 2024-08-14 12:31
tried with ghub closed and the bug keeps occurring.

**Comment by minteeaa** [comment] 2024-08-14 12:35
can you provide a few more details on your setup? (keyboard layout, your config, primarily) 

can try to replicate

**Comment by VickyVexx** [comment] 2024-08-14 12:42
Keyboard layout is QWERTZ (German Layout)
I don't know what exactly you mean by Config
i didn't change anything but the lighting

**Comment by minteeaa** [comment] 2024-08-14 12:46
your snapkey config, the groups and keys bound within

**Comment by VickyVexx** [comment] 2024-08-14 13:13
No specific key combination, didnt change the config at all

**Comment by arthurcgc** [comment] 2024-08-14 14:10
I'm having the same issue, but while playing CS2 (the superior fps 😆). Seems like a key gets "stuck"... I also use a logitech keyboard.

**Comment by cafali** [comment] 2024-08-14 14:13
sounds like a ghosting issue to me

https://github.com/cafali/SnapKey/wiki/Troubleshoot#p5-keyboard-ghosting-hardware-limitation

**Comment by minteeaa** [comment] 2024-08-14 14:15
the G213 is advertised with anti-ghost, but not NKRO. 

> I'm having the same issue, but while playing CS2 (the superior fps 😆). Seems like a key gets "stuck"... I also use a logitech keyboard.

can you confirm if your keyboard is advertised to have anti-ghost or NKRO?

if both are having issues with the ALT key, it's worth looking into i'd say - ALT modifier can screw with key inputs to the system;

**Comment by arthurcgc** [comment] 2024-08-14 14:16
@cafali it's not though, my keyboard is a Logitech G512

**Comment by minteeaa** [comment] 2024-08-14 14:18
G512 advertised to have NKRO and anti-ghost; this is likely an issue with the ALT modifier in key handling

**Comment by minteeaa** [comment] 2024-08-14 14:22
it could just be ALT, tbh I don't see a reason for this to be a ghosting issue regarding the ALT modifier when it's just that and the movement keys - I'll do some testing with it on different layouts to confirm any further

@arthurcgc just to make sure, what keyboard layout do you use?

**Comment by arthurcgc** [comment] 2024-08-14 14:24
@minteeaa QWERTY layout

**Comment by minteeaa** [comment] 2024-08-14 14:25
noted, I'd say for now probably don't use ALT if possible - more info to come if the issue can be reproduced locally

**Comment by cafali** [comment] 2024-08-14 14:31
can confirm, just got home and tested it - Razer Blackwidow V3 QWERTY/QWERTZ

**Comment by arthurcgc** [comment] 2024-08-14 15:00
yeah, now that you guys mentioned it, it makes total sense that it has something to do with the ALT modifiers... When I hop into DM servers everything runs smoothly, since I only use ALT keys to pull out grenades it happens almost exclusively while playing comp.

**Comment by VickyVexx** [comment] 2024-08-14 15:08
ghosting sounds to me like it's an entirely different issue since it's not about keys not registering but i'm by no means even slightly educated about how keyboards actually work.

so the solution seems to be to rebind walk to not use ALT and wait for you guys to test around and Update SnapKey:

i really respect the work you are doing and thank you for your speedy replies. awesome

**Comment by cafali** [comment] 2024-08-15 05:51
Hey everyone, we've found a new bug with the Shift key. The ALT issue should be fixed now. We're just waiting on a Shift hotfix, and then we'll release the updated version.

**Comment by cafali** [comment] 2024-08-15 06:27
v1.2.1 is live!
[Download SnapKey 1.2.1](https://github.com/cafali/SnapKey/releases/tag/v1.2.1)

SnapKey 1.2.1

Bugfixes:

- ALT Key: Adressed an Issue with the ALT key - when you hold ALT and then Press any key with the SnapKey function, the key will remain pressed. This Issue should be fixed now.

- Shift Key: Fixed an issue where the Shift key was not being detected correctly.

Others:
- Updated versioninfo file
- Updated version file

**Comment by VickyVexx** [comment] 2024-08-15 11:43
you guys are the best <3

**Closed** 2024-08-15 13:26 UTC
Labels: bug, fixed
