### ISSUE TITLE
The program cannot work continuously

### ISSUE THREAD

**Issue by zhoouzhe** [cafali/SnapKey#42] opened 2024-08-07 05:15 UTC
After completing a CS2 game, I will use https://drakeirving.github.io/MultiKeyDisplay/ This website is being tested, and A and D can be typed simultaneously unless I restart the program

**Comment by cafali** [comment] 2024-08-07 06:13
I don't know if I understood your problem correctly. When you complete a CS2 game, will you then test SnapKey on the [MultiKeyDisplay](https://drakeirving.github.io/MultiKeyDisplay/) website? Also, SnapKey can run continuously; when SnapKey is running, pressing two keys from the same group (A/D or W/S) is not possible. 

A will cancel D, and W will cancel S, and vice versa. 

I’m not really sure what your issue is since it’s described a bit unclearly. 

Also, make sure you are using the latest version of Snapkey.
For more information about troubleshooting, you can visit: [SnapKey Troubleshooting](https://github.com/cafali/SnapKey/wiki).

**Comment by zhoouzhe** [comment] 2024-08-07 06:54
Sorry, my English is not very good.
As you said, I will conduct the test after completing one game, and the test result shows that A and D can be typed simultaneously.However, the program runs normally before starting the game.

**Comment by zhoouzhe** [comment] 2024-08-07 06:56
I using the latest version of Snapkey which is 1.1.8

**Comment by cafali** [comment] 2024-08-07 07:11
Can you consistently reproduce the issue by following specific steps? If so, what are those steps?

**Comment by zhoouzhe** [comment] 2024-08-07 07:39
1.Before starting the game,the test result shows the program runs normally.
2.When I switched to the testing website while in the game, the test results were unstable and initially abnormal, but after pressing the A and D keys a few more times, they returned to normal.
3.After completing one game,A can't cancel D.It only returns to normal when I restart the program.

**Comment by zhoouzhe** [comment] 2024-08-07 07:40
I hope I have expressed the problem clearly

**Comment by cafali** [comment] 2024-08-07 14:21
I tested the reported issue in CS2 with both a high-end gaming keyboard and an office keyboard for 10$. 

Also, since I don’t have any specifics about your hardware/drivers/windows version, it’s hard to know if that’s playing a part.

I could not replicate the problem under any conditions, including when the game was running in the background or while alt-tabbing in fullscreen and borderless mode, even after relaunching the game.

On my end, SnapKey is running flawlessly, both during load and while idle.

Since the "bug" could not be replicated, I will be closing this issue.

**Closed by cafali** 2024-08-07 14:21 UTC
Labels: bug, unclear, irreplicable

**Comment by zhoouzhe** [comment] 2024-08-08 01:31
I think I have identified the problem and found similar issues on the forum. It should be a problem with China's CS2 gaming platform, also known as the Perfect World competitive platform. Other gaming platforms do not have this phenomenon.

**Comment by zhoouzhe** [comment] 2024-08-08 01:35
![e5a7563edca5fe4b109676f3e8fab65](https://github.com/user-attachments/assets/2da37681-5695-41aa-bcd6-78404599b7a0)
